/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as EquipmentIndexRouteImport } from './routes/equipment/index'
import { Route as EquipmentAddRouteImport } from './routes/equipment/add'
import { Route as EquipmentEditIdRouteImport } from './routes/equipment/edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentAddRoute = EquipmentAddRouteImport.update({
  id: '/equipment/add',
  path: '/equipment/add',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentEditIdRoute = EquipmentEditIdRouteImport.update({
  id: '/equipment/edit/$id',
  path: '/equipment/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/labs': typeof LabsRoute
  '/my-requests': typeof MyRequestsRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/equipment/add': typeof EquipmentAddRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/equipment/edit/$id': typeof EquipmentEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/labs': typeof LabsRoute
  '/my-requests': typeof MyRequestsRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/equipment/add': typeof EquipmentAddRoute
  '/equipment': typeof EquipmentIndexRoute
  '/equipment/edit/$id': typeof EquipmentEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/labs': typeof LabsRoute
  '/my-requests': typeof MyRequestsRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/equipment/add': typeof EquipmentAddRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/equipment/edit/$id': typeof EquipmentEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/labs'
    | '/my-requests'
    | '/requests'
    | '/signup'
    | '/equipment/add'
    | '/equipment/'
    | '/equipment/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/labs'
    | '/my-requests'
    | '/requests'
    | '/signup'
    | '/equipment/add'
    | '/equipment'
    | '/equipment/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/labs'
    | '/my-requests'
    | '/requests'
    | '/signup'
    | '/equipment/add'
    | '/equipment/'
    | '/equipment/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LabsRoute: typeof LabsRoute
  MyRequestsRoute: typeof MyRequestsRoute
  RequestsRoute: typeof RequestsRoute
  SignupRoute: typeof SignupRoute
  EquipmentAddRoute: typeof EquipmentAddRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
  EquipmentEditIdRoute: typeof EquipmentEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/add': {
      id: '/equipment/add'
      path: '/equipment/add'
      fullPath: '/equipment/add'
      preLoaderRoute: typeof EquipmentAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/edit/$id': {
      id: '/equipment/edit/$id'
      path: '/equipment/edit/$id'
      fullPath: '/equipment/edit/$id'
      preLoaderRoute: typeof EquipmentEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LabsRoute: LabsRoute,
  MyRequestsRoute: MyRequestsRoute,
  RequestsRoute: RequestsRoute,
  SignupRoute: SignupRoute,
  EquipmentAddRoute: EquipmentAddRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
  EquipmentEditIdRoute: EquipmentEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
